// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YemekDünyasi.Models;

#nullable disable

namespace YemekDünyasi.Migrations
{
    [DbContext(typeof(YemekDünyasContext))]
    partial class YemekDünyasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("YemekDünyasi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("KategoriResimUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoryTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KategoriResimUrl = "https://avatarfiles.alphacoders.com/324/324948.jpg",
                            Name = "Döner"
                        },
                        new
                        {
                            Id = 2,
                            KategoriResimUrl = "https://avatarfiles.alphacoders.com/155/thumb-155431.jpg",
                            Name = "Burger"
                        },
                        new
                        {
                            Id = 3,
                            KategoriResimUrl = "https://avatarfiles.alphacoders.com/977/thumb-97720.jpg",
                            Name = "Tavuk"
                        },
                        new
                        {
                            Id = 4,
                            KategoriResimUrl = "https://avatarfiles.alphacoders.com/153/153723.jpg",
                            Name = "Pasta&Tatlı"
                        },
                        new
                        {
                            Id = 5,
                            KategoriResimUrl = "https://avatarfiles.alphacoders.com/321/321978.jpg",
                            Name = "Tost&Sandviç"
                        },
                        new
                        {
                            Id = 6,
                            KategoriResimUrl = "https://i4.hurimg.com/i/hurriyet/75/750x422/628670424e3fe02cd0cd9919.jpg",
                            Name = "Sokak Lezzetleri"
                        },
                        new
                        {
                            Id = 7,
                            KategoriResimUrl = "https://cdn.yemek.com/mncrop/940/625/uploads/2016/05/adana-kebap-one-cikan.jpg",
                            Name = "Kebap"
                        },
                        new
                        {
                            Id = 8,
                            KategoriResimUrl = "https://avatarfiles.alphacoders.com/341/341145.jpg",
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = 9,
                            KategoriResimUrl = "https://images.deliveryhero.io/image/fd-tr/LH/vrjp-hero.jpg",
                            Name = "Pide"
                        },
                        new
                        {
                            Id = 10,
                            KategoriResimUrl = "https://www.elizinn.com.tr/wp-content/uploads/2022/11/kh1-600x597.jpg",
                            Name = "Kahvaltı"
                        },
                        new
                        {
                            Id = 11,
                            KategoriResimUrl = "https://cdn.yemek.com/mncrop/940/625/uploads/2020/04/lahmacun-yeni-one-cikan.jpg",
                            Name = "Lahmacun"
                        },
                        new
                        {
                            Id = 12,
                            KategoriResimUrl = "https://cdn.yemek.com/mncrop/940/625/uploads/2014/10/tas-kebabi-yemekcom.jpg",
                            Name = "Ev yemekleri"
                        },
                        new
                        {
                            Id = 13,
                            KategoriResimUrl = "https://cdn.yemek.com/mncrop/940/625/uploads/2015/07/kaffeform.jpg",
                            Name = "Kahve"
                        },
                        new
                        {
                            Id = 14,
                            KategoriResimUrl = "https://cdn.yemek.com/mncrop/940/625/uploads/2020/03/vejetaryen-carpaccio-editor.jpg",
                            Name = "Vejetaryen"
                        },
                        new
                        {
                            Id = 15,
                            KategoriResimUrl = "https://cdn.yemek.com/mncrop/940/625/uploads/2016/02/inanclarina-gore-mezhep-aliskanliklari.jpg",
                            Name = "Dünya Mutfağı"
                        },
                        new
                        {
                            Id = 16,
                            KategoriResimUrl = "https://cdn.yemek.com/mnresize/1250/833/uploads/2022/03/ev-koftesi-yemekcom.jpg",
                            Name = "Köfte"
                        },
                        new
                        {
                            Id = 17,
                            KategoriResimUrl = "https://cdn.yemek.com/mnresize/1250/833/uploads/2022/09/10-dakikada-peynirli-borek-onecikan.jpg",
                            Name = "Börek"
                        },
                        new
                        {
                            Id = 18,
                            KategoriResimUrl = "https://cdn.yemek.com/mncrop/940/625/uploads/2019/03/etsiz-cig-kofte-yeni.jpg",
                            Name = "Çiğ Köfte"
                        },
                        new
                        {
                            Id = 19,
                            KategoriResimUrl = "https://cdn.yemek.com/mncrop/620/388/uploads/2021/07/coban-salata-one-cikan.jpg",
                            Name = "Salata"
                        },
                        new
                        {
                            Id = 20,
                            KategoriResimUrl = "https://cdn.yemek.com/mncrop/620/388/uploads/2020/08/limonlu-soguk-cay-sunum.jpg",
                            Name = "İçecek"
                        },
                        new
                        {
                            Id = 21,
                            KategoriResimUrl = "https://cdn.yemek.com/mncrop/620/388/uploads/2016/11/balik-pisirmek-koku-shutter-2022.jpg",
                            Name = "Deniz Ürünleri"
                        },
                        new
                        {
                            Id = 22,
                            KategoriResimUrl = "https://cdn.yemek.com/mncrop/620/388/uploads/2015/04/olmeden-yenmesi-gereken-dondurmalar.jpg",
                            Name = "Dondurma"
                        });
                });

            modelBuilder.Entity("YemekDünyasi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("UserId");

                    b.ToTable("OrderTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderDate = new DateTime(2023, 8, 2, 12, 31, 49, 657, DateTimeKind.Local).AddTicks(8823),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderDate = new DateTime(2023, 8, 2, 12, 31, 49, 657, DateTimeKind.Local).AddTicks(8824),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            OrderDate = new DateTime(2023, 8, 2, 12, 31, 49, 657, DateTimeKind.Local).AddTicks(8825),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            OrderDate = new DateTime(2023, 8, 2, 12, 31, 49, 657, DateTimeKind.Local).AddTicks(8826),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            OrderDate = new DateTime(2023, 8, 2, 12, 31, 49, 657, DateTimeKind.Local).AddTicks(8826),
                            UserId = 5
                        });
                });

            modelBuilder.Entity("YemekDünyasi.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItemTable");
                });

            modelBuilder.Entity("YemekDünyasi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<string>("UrunResimUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("ProductTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Info = "1 Porsiyon(100 gr Döner Eti)",
                            Name = "İskender",
                            Price = 250m,
                            RestaurantId = 111,
                            UrunResimUrl = "https://www.diyetkolik.com/site_media/media/2019/11/01/iskender-kebap.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 7,
                            Info = "1 Porsion (200gr)",
                            Name = "Kuzu Şiş",
                            Price = 230m,
                            RestaurantId = 111,
                            UrunResimUrl = "https://i4.hurimg.com/i/hurriyet/75/750x422/60dc62dec9de3d3820d4722e.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Info = "1 Porsion (200gr)",
                            Name = "Tavuk Şiş",
                            Price = 120m,
                            RestaurantId = 111,
                            UrunResimUrl = "https://cdn.tarifikolay.com/public/tt/uploads/2022/kuzu-sis_2204-730x548.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 7,
                            Info = "1 Porsion (200gr)",
                            Name = "Beyti",
                            Price = 155m,
                            RestaurantId = 111,
                            UrunResimUrl = "https://i2.milimaj.com/i/milliyet/75/0x410/5ed105ce5542820f10d423b6.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 7,
                            Info = "1 Porsion (100gr Kıyma)",
                            Name = "Alinazik",
                            Price = 160m,
                            RestaurantId = 111,
                            UrunResimUrl = "https://menu.seyridem.com/upload/11389856076552836344.jpeg"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 13,
                            Info = "Süt, çikolata sosu ve kar haline getirilmiş buzun krema ve üzerine çikolata sosu ile süslenerek sunulması",
                            Name = "Chocolate Cream Frappuccino",
                            Price = 80m,
                            RestaurantId = 124,
                            UrunResimUrl = "https://api.sbux.retter.io/3e898s82a/CALL/Image/get/SBUX-58_720x720.png"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 13,
                            Info = "Baharatlı Siyah Çay Özlü Latte) Baharatlar ve siyah çay karışımının, su ile inceltilmesi ardından buharla ısıtılmış kadifemsi süt ile buluşması",
                            Name = "Chai Tea Latte",
                            Price = 69m,
                            RestaurantId = 124,
                            UrunResimUrl = "https://api.sbux.retter.io/3e898s82a/CALL/Image/get/SBUX-40_720x720.png"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 13,
                            Info = "(Karamel Şuruplu Sıcak Çikolata) Buharla ısıtılmış süt, karamel şurubu ve tarifi Starbucksa özel çikolata sosunun buluşmasıyla ortaya çıkan tatlı lezzet",
                            Name = "Signature Caramel Hot Chocolate",
                            Price = 55m,
                            RestaurantId = 124,
                            UrunResimUrl = "https://api.sbux.retter.io/3e898s82a/CALL/Image/get/SBUX-62_720x720.png"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Info = "Pandispanya ve kahveli kremanın beyaz çikolata ile buluştuğu fındık parçacıklarıyla kaplı pasta",
                            Name = "Kahveli Pasta",
                            Price = 45m,
                            RestaurantId = 124,
                            UrunResimUrl = "https://api.sbux.retter.io/3e898s82a/CALL/Image/get/SBUX-104_720x720.png"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Info = "Whopper® eti, büyük boy susamlı sandviç ekmeği, salatalık turşusu, ketçap, mayonez, doğranmış marul, domates ve soğandan oluşan bir Burger King® klasiği. Enfes patates kızartması ve içeceğiyle birlikte Whopper® Menü keyfini istediğin gibi yaşa!",
                            Name = "Whopper® Menü",
                            Price = 150m,
                            RestaurantId = 128,
                            UrunResimUrl = "https://www.burgerking.com.tr/cmsfiles/products/whopper-menu.png?v=273"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Info = "Bir Burger King Klasiği, 6’lı ya da 9 parça çıtır BK King Nuggets®",
                            Name = "BK King Nuggets",
                            Price = 60m,
                            RestaurantId = 128,
                            UrunResimUrl = "https://www.burgerking.com.tr/cmsfiles/products/bk-king-nuggets-1.png?v=273"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Info = "Hamburger eti, küçük boy susamlı sandviç ekmeği, salatalık turşusu, hardal ve ketçaptan oluşan lezzet. Enfes patates kızartması ve içeceğiyle birlikte Hamburger Menü keyfini istediğin gibi yaşa!",
                            Name = "Hamburger Menü",
                            Price = 135m,
                            RestaurantId = 128,
                            UrunResimUrl = "https://www.burgerking.com.tr/cmsfiles/products/hamburger-menu.png?v=273"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 8,
                            Info = "Pizza sosu, mozzarella peyniri, salam, mantar",
                            Name = "Çiftlik Evi",
                            Price = 135m,
                            RestaurantId = 112,
                            UrunResimUrl = "https://www.pizzahut.com.tr/CMSFiles/Product/LittleImage/ciftlik-evi_638138698051152285.jpg"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 8,
                            Info = "Pizza sosu, mozzarella peyniri, salam, sucuk, sosis, yeşilbiber, mantar, mısır",
                            Name = "Karışık",
                            Price = 169m,
                            RestaurantId = 112,
                            UrunResimUrl = "https://www.pizzahut.com.tr/CMSFiles/Product/LittleImage/karisik_638138711642553787.jpg"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 8,
                            Info = "Pizza sosu, mozzarella peyniri, pepperoni, sucuk, sosis, salam, yeşilbiber, mantar, siyah zeytin, mısır, domates, kekik, susam",
                            Name = "Superboll Pizza",
                            Price = 161m,
                            RestaurantId = 112,
                            UrunResimUrl = "https://www.pizzahut.com.tr/CMSFiles/Product/LittleImage/superboll-pizza.jpg"
                        });
                });

            modelBuilder.Entity("YemekDünyasi.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestResimUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("RestaurantTable");

                    b.HasData(
                        new
                        {
                            Id = 111,
                            Address = "Batıkent",
                            Name = "Ala kebap",
                            RestResimUrl = "https://www.alaiskembe.com/wp-content/uploads/2021/11/alaiskembe-halkali-min.jpg",
                            TelNo = "08505678990"
                        },
                        new
                        {
                            Id = 112,
                            Address = "Kızılay",
                            Name = "Lezzet Sofrası",
                            RestResimUrl = "https://media-cdn.tripadvisor.com/media/photo-s/17/72/ef/b8/kapadokya-lezzet-sofrasi.jpg",
                            TelNo = "03123456789"
                        },
                        new
                        {
                            Id = 113,
                            Address = "Çankaya",
                            Name = "Pizza Evi",
                            RestResimUrl = "https://img.freepik.com/premium-vector/pizza-house-logo-template-flat-design-style_180868-2435.jpg",
                            TelNo = "03127894561"
                        },
                        new
                        {
                            Id = 114,
                            Address = "Bahçelievler",
                            Name = "Burger Land",
                            RestResimUrl = "https://family-images-y24bv7yxalct4.azureedge.net/families/7625/7625_homescreenlogo_1024x1024.jpg",
                            TelNo = "03125678321"
                        },
                        new
                        {
                            Id = 115,
                            Address = "Gölbaşı",
                            Name = "Nefis Deniz Mahsülleri",
                            RestResimUrl = "https://i.nefisyemektarifleri.com/2016/12/26/balik-firinda-izgara-tadinda.jpeg",
                            TelNo = "03123450987"
                        },
                        new
                        {
                            Id = 116,
                            Address = "Etimesgut",
                            Name = "Tostçudayım",
                            RestResimUrl = "https://www.ismailtoparli.com/dosyalar/ismailtoparli/yukle/sektorler/tostcu/tostcu7.jpg",
                            TelNo = "03127895678"
                        },
                        new
                        {
                            Id = 117,
                            Address = "Tunalı Hilmi",
                            Name = "Mehmet Efendi",
                            RestResimUrl = "https://upload.wikimedia.org/wikipedia/tr/d/d0/Kurukahveci_Mehmet_Efendi_Logo.jpeg",
                            TelNo = "03125678901"
                        },
                        new
                        {
                            Id = 118,
                            Address = "Ankara Üniversitesi",
                            Name = "Fırıncı Temel",
                            RestResimUrl = "https://d1hzl1rkxaqvcd.cloudfront.net/contest_entries/2119929/_300px/50e9dbe9b169fee1ac2182abaac93b19.jpg",
                            TelNo = "03123456789"
                        },
                        new
                        {
                            Id = 119,
                            Address = "Yıldırım Beyazıt Üniversitesi",
                            Name = "Menemen Kahvaltı Salonu",
                            RestResimUrl = "https://d1hzl1rkxaqvcd.cloudfront.net/contest_entries/1867941/_300px/a7eada0a1e9113bf555fcf4e5545990c.jpg",
                            TelNo = "03127894567"
                        },
                        new
                        {
                            Id = 120,
                            Address = "Cebeci",
                            Name = "Lahmacun Dükkanı",
                            RestResimUrl = "https://st2.depositphotos.com/1007499/5212/v/450/depositphotos_52120603-stock-illustration-turkish-food-lahmacun-stamp.jpg",
                            TelNo = "03125678912"
                        },
                        new
                        {
                            Id = 121,
                            Address = "Ulus",
                            Name = "Yasemin Pastanesi",
                            RestResimUrl = "https://i.pinimg.com/736x/46/a0/53/46a053c1ddec57f6c41b9560fcc0f04a.jpg",
                            TelNo = "08974452214"
                        },
                        new
                        {
                            Id = 122,
                            Address = "Çankaya",
                            Name = "Vefa Bozacısı",
                            RestResimUrl = "https://yuzyillikhikayeler.com/wp-content/uploads/2022/08/vefa-bozacisi-logo.jpg",
                            TelNo = "04563457788"
                        },
                        new
                        {
                            Id = 123,
                            Address = "Batıkent",
                            Name = "Adıyaman çiğköfte",
                            RestResimUrl = "https://www.ramazanaltug.com.tr/assets/images/adyamancigkoftekrmzkare01-1270x953.jpg",
                            TelNo = "02224567767"
                        },
                        new
                        {
                            Id = 124,
                            Address = "Yenimahalle",
                            Name = "Starbucks",
                            RestResimUrl = "https://e1.pxfuel.com/desktop-wallpaper/23/400/desktop-wallpaper-starbucks-coffee-logo-starbucks-logo-thumbnail.jpg",
                            TelNo = "05785554475"
                        },
                        new
                        {
                            Id = 125,
                            Address = "Pursaklar",
                            Name = "Lezzet Döner",
                            RestResimUrl = "https://cdn1.tasarlatasarlat.com/desings/e0/28/795/d900d160f7456bc1ece8e711b.jpg",
                            TelNo = "02345556787"
                        },
                        new
                        {
                            Id = 126,
                            Address = "Ostim",
                            Name = "Dünya Döner",
                            RestResimUrl = "https://www.dunyadoner.com.tr/Upload/File/2020/2/6/dunyadonerlogo1.png",
                            TelNo = "04665678799"
                        },
                        new
                        {
                            Id = 127,
                            Address = "Batıkent",
                            Name = "Paşa Döner",
                            RestResimUrl = "https://seeklogo.com/images/P/pasa-doner-logo-B8F59C9E94-seeklogo.com.png",
                            TelNo = "02556547766"
                        },
                        new
                        {
                            Id = 128,
                            Address = "Batıkent",
                            Name = "Burger King",
                            RestResimUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Burger_King_logo_(1999).svg/512px-Burger_King_logo_(1999).svg.png",
                            TelNo = "08987543355"
                        });
                });

            modelBuilder.Entity("YemekDünyasi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserResimUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsersTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "Batıkent",
                            Email = "Durayse@gmail.com",
                            Name = "Ayşe",
                            Password = "jhngbvffh",
                            Surname = "Duran",
                            TelNo = "05434346578",
                            UserResimUrl = "https://avatarfiles.alphacoders.com/349/349625.png"
                        },
                        new
                        {
                            Id = 2,
                            Adress = "Ümitköy",
                            Email = "Durayse@gmail.com",
                            Name = "Ai",
                            Password = "jhngbvffh",
                            Surname = "Kaşcı",
                            TelNo = "05434346578",
                            UserResimUrl = "https://avatarfiles.alphacoders.com/348/348381.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Adress = "Çamlıca",
                            Email = "ahmet1987@gmail.com",
                            Name = "Ahmet",
                            Password = "jhngbvffh",
                            Surname = "Satır",
                            TelNo = "05434346579",
                            UserResimUrl = "https://avatarfiles.alphacoders.com/349/349379.png"
                        },
                        new
                        {
                            Id = 4,
                            Adress = "Sıhiyye",
                            Email = "12345@gmail.com",
                            Name = "Kemal",
                            Password = "jhngbvffh",
                            Surname = "Kuru",
                            TelNo = "05434346574",
                            UserResimUrl = "https://avatarfiles.alphacoders.com/893/89303.gif"
                        },
                        new
                        {
                            Id = 5,
                            Adress = "Ulus",
                            Email = "sk1234@gmail.com",
                            Name = "Selvi",
                            Password = "jhngbvffh",
                            Surname = "Kara",
                            TelNo = "05434346573",
                            UserResimUrl = "https://avatarfiles.alphacoders.com/896/89615.png"
                        },
                        new
                        {
                            Id = 6,
                            Adress = "Etimesgut",
                            Email = "2Mel@gmail.com",
                            Name = "Melih",
                            Password = "jhngbvffh",
                            Surname = "Mutlu",
                            TelNo = "05434346575",
                            UserResimUrl = "https://avatarfiles.alphacoders.com/349/thumb-349931.png"
                        },
                        new
                        {
                            Id = 7,
                            Adress = "Bahçelievler",
                            Email = "taskadir@gmail.com",
                            Name = "Kadir",
                            Password = "jhngbvffh",
                            Surname = "Taş",
                            TelNo = "05434346570",
                            UserResimUrl = "https://avatarfiles.alphacoders.com/350/350226.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Adress = "Emek",
                            Email = "elifs@gmail.com",
                            Name = "Elif",
                            Password = "jhngbvffh",
                            Surname = "Salkım",
                            TelNo = "05434346572",
                            UserResimUrl = "https://avatarfiles.alphacoders.com/543/54363.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Adress = "Mamak",
                            Email = "daylin@gmail.com",
                            Name = "aylin",
                            Password = "jhngbvffh",
                            Surname = "Durmuş",
                            TelNo = "05434346571",
                            UserResimUrl = "https://avatarfiles.alphacoders.com/613/61339.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Adress = "Batımerkez",
                            Email = "kalden@gmail.com",
                            Name = "Deniz",
                            Password = "jhngbvffh",
                            Surname = "Kaleci",
                            TelNo = "05434346576",
                            UserResimUrl = "https://avatarfiles.alphacoders.com/350/350631.jpeg"
                        });
                });

            modelBuilder.Entity("YemekDünyasi.Models.UserSepet", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("UserSepetTable");
                });

            modelBuilder.Entity("YemekDünyasi.Models.Order", b =>
                {
                    b.HasOne("YemekDünyasi.Models.Restaurant", null)
                        .WithMany("Orders")
                        .HasForeignKey("RestaurantId");

                    b.HasOne("YemekDünyasi.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YemekDünyasi.Models.OrderItem", b =>
                {
                    b.HasOne("YemekDünyasi.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YemekDünyasi.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("YemekDünyasi.Models.Product", b =>
                {
                    b.HasOne("YemekDünyasi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YemekDünyasi.Models.Restaurant", "Restaurant")
                        .WithMany("Products")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("YemekDünyasi.Models.Restaurant", b =>
                {
                    b.HasOne("YemekDünyasi.Models.Category", null)
                        .WithMany("Restaurants")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("YemekDünyasi.Models.UserSepet", b =>
                {
                    b.HasOne("YemekDünyasi.Models.Product", "Product")
                        .WithMany("UserCarts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YemekDünyasi.Models.User", "User")
                        .WithMany("UserSepets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YemekDünyasi.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("YemekDünyasi.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("YemekDünyasi.Models.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("UserCarts");
                });

            modelBuilder.Entity("YemekDünyasi.Models.Restaurant", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("YemekDünyasi.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("UserSepets");
                });
#pragma warning restore 612, 618
        }
    }
}
